/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Radio, FormControlLabel, TextField, Button } from '@mui/material';
import XImage from 'src/assets/images/CancelAccount_x.png';
import { styled } from '@mui/material/styles';
import { CancelAccountProps } from 'src/types';

 
const Property1Default: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `40px 30px`,  
  boxSizing: `border-box`,  
});
  
const TopWithX: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TopSec: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const WeReSorryToSeeYouGo: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(39, 39, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `359px`,  
  margin: `0px`,  
});
  
const WhyAreYouCancelling: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(39, 39, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `17px`,  
  textTransform: `none`,  
  margin: `6px 0px 0px 0px`,  
});
  
const Divider: any = styled("div")({  
  backgroundColor: `rgba(218, 218, 218, 1)`,  
  alignSelf: `stretch`,  
  height: `1px`,  
  margin: `30px 0px 0px 0px`,  
});
  
const X: any = styled("img")({  
  height: `12px`,  
  width: `12px`,  
});
  
const OptionsAndReason: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `22px 0px 0px 0px`,  
});
  
const Options: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const FormControlLabel1: any = styled(FormControlLabel)({  
  margin: `0px`,  
});
  
const FormControlLabel2: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const FormControlLabel3: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const FormControlLabel4: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const FormControlLabel5: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const FormControlLabel6: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const FormControlLabel7: any = styled(FormControlLabel)({  
  margin: `4px 0px 0px 0px`,  
});
  
const OtherReason: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 12px`,  
  boxSizing: `border-box`,  
  margin: `-4px 0px 0px 0px`,  
});
  
const TextFieldStandard: any = styled(TextField)({  
  width: `367px`,  
  margin: `0px`,  
});
  
const Botom: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `16px 0px 0px 10px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `22px 0px 0px 0px`,  
});
  
const AreYouSureYouWantToD: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(39, 39, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `17px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const SubmitCancel: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 10px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const ButtonContained: any = styled(Button)({  
  margin: `0px`,  
});
  
const ButtonText: any = styled(Button)({  
  margin: `0px 0px 0px 26px`,  
});
 
function CancelAccount(props: CancelAccountProps): JSX.Element {
  return (
    <Property1Default className={props.className} >
      <TopWithX >
        <TopSec >
          <Top >
            <WeReSorryToSeeYouGo >
              {`We’re sorry to see you go!`}
                </WeReSorryToSeeYouGo>
            <WhyAreYouCancelling >
              {`Why are you cancelling?`}
                </WhyAreYouCancelling>
          </Top>
          <Divider >
          </Divider>
        </TopSec>
        <X  src={XImage} alt={"x"}/>
      </TopWithX>
      <OptionsAndReason >
        <Options >
          <FormControlLabel1 control={<Radio id={"test-miu-id"}  color="primary" size="medium" inputProps={{"aria-label": "test-mui"}} />} label={"Didn't use enough"} />
          <FormControlLabel2 control={<Radio color="primary" size="medium" />} label={"Too expensive"} />
          <FormControlLabel3 control={<Radio color="primary" size="medium" />} label={"Hard to use"} />
          <FormControlLabel4 control={<Radio color="primary" size="medium" />} label={"Switching from personal to a corporate account"} />
          <FormControlLabel5 control={<Radio color="primary" size="medium" />} label={"Poor customer service"} />
          <FormControlLabel6 control={<Radio color="primary" size="medium" />} label={"Missing features (Please mention the missing features below)"} />
          <FormControlLabel7 control={<Radio color="primary" size="medium" />} label={"Other"} />
        </Options>
        <OtherReason id={"super-id"}   aria-label={"label"}  aria-labelledby={labelled-by}  aria-describedby={"described"} >
          <TextFieldStandard variant="standard" size="medium"  label={`Reason for cancelling`}    />
        </OtherReason>
      </OptionsAndReason>
      <Botom >
        <AreYouSureYouWantToD >
          {`Are you sure you want to delete your account? This cannot be undone.`}
            </AreYouSureYouWantToD>
        <SubmitCancel >
          <ButtonContained variant="contained" size="medium" color="primary"    > Go Back </ButtonContained>
          <ButtonText variant="text" size="medium" color="primary"    > Confirm Cancel Account </ButtonText>
        </SubmitCancel>
      </Botom>
    </Property1Default>
  );
}

export default CancelAccount;
