/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import Image1Image from 'src/assets/images/demotestframe2_image_1.png';
import { styled } from '@mui/material/styles';
import { DemoTestFrame2Props } from 'src/types';

 
const DemoTestFrame21: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Hhhhhh: any = styled("div")(({ theme }: any) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: theme.typography["Components"]["Avatar Initials"].fontStyle,  
  fontFamily: theme.typography["Components"]["Avatar Initials"].fontFamily,  
  fontWeight: theme.typography["Components"]["Avatar Initials"].fontWeight,  
  fontSize: theme.typography["Components"]["Avatar Initials"].fontSize,  
  letterSpacing: theme.typography["Components"]["Avatar Initials"].letterSpacing,  
  textDecoration: theme.typography["Components"]["Avatar Initials"].textDecoration,  
  lineHeight: theme.typography["Components"]["Avatar Initials"].lineHeight,  
  textTransform: theme.typography["Components"]["Avatar Initials"].textTransform,  
  position: `absolute`,  
  left: `49px`,  
  top: `53px`,  
}));
  
const Image1: any = styled("img")({  
  height: `58px`,  
  width: `175px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `48px`,  
  top: `90px`,  
});
 
function DemoTestFrame2(props: DemoTestFrame2Props): JSX.Element {
  return (
    <DemoTestFrame21 className={props.className} >
      <Hhhhhh >
        {`hhhhhh`}
          </Hhhhhh>
      <Image1  src={Image1Image} alt={"image 1"}/>
    </DemoTestFrame21>
  );
}

export default DemoTestFrame2;
